model_type: xr1_ppo
model_path: ${oc.env:XR1_ROBOCASA365_CKPT,${oc.env:REPO_PATH}/checkpoints/Xiaomi-Robotics-1-RoboCasa365}
precision: bf16
is_lora: false
lora_rank: 32
lora_path: null
trust_remote_code: true
load_to_device: true
local_files_only: true
attn_implementation: eager
action_dim: 60
num_action_chunks: 16
action_horizon: 16
env_action_dim: 12
state_dim: 60
state_length: 4
video_history: 4
history_interval: 2
crop_ratio: 0.95
robot_type: robocasa365
decode_actions: true
add_value_head: true
action_std: 0.2
likelihood_mode: gaussian
flow_trace_samples: 1
learn_action_std: false
clip_normalized_action: 1.5
num_steps: 5
trainable_mode: full
